#ifndef LCD_IMAGES_H
#define LCD_IMAGES_H

#include <stdint.h>

#define LCD_IMAGE_WIDTH   320U
#define LCD_IMAGE_HEIGHT  240U

extern const uint16_t LCD_SAFE_IMAGE[LCD_IMAGE_WIDTH * LCD_IMAGE_HEIGHT];
extern const uint16_t LCD_LEVEL1_IMAGE[LCD_IMAGE_WIDTH * LCD_IMAGE_HEIGHT];
extern const uint16_t LCD_LEVEL2_IMAGE[LCD_IMAGE_WIDTH * LCD_IMAGE_HEIGHT];
extern const uint16_t LCD_LEVEL3_IMAGE[LCD_IMAGE_WIDTH * LCD_IMAGE_HEIGHT];
extern const uint16_t LCD_SYSTEM_ERROR_IMAGE[LCD_IMAGE_WIDTH * LCD_IMAGE_HEIGHT];

#endif /* LCD_IMAGES_H */